/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-d1-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
  type AnySQLiteColumn,
} from '@payloadcms/db-d1-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-d1-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    aadObjectId: text('aad_object_id').notNull(),
    displayName: text('display_name').notNull(),
    givenName: text('given_name'),
    surname: text('surname'),
    jobTitle: text('job_title'),
    department: text('department'),
    role: text('role', { enum: ['staff', 'policy_staff', 'admin'] })
      .notNull()
      .default('staff'),
    isActive: integer('is_active', { mode: 'boolean' }).default(true),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('users_aad_object_id_idx').on(columns.aadObjectId),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const projects = sqliteTable(
  'projects',
  {
    id: integer('id').primaryKey(),
    code: text('code'),
    name: text('name').notNull(),
    description: text('description'),
    status: text('status', { enum: ['planned', 'active', 'on_hold', 'completed', 'cancelled'] })
      .notNull()
      .default('planned'),
    priority: text('priority', { enum: ['low', 'medium', 'high', 'urgent'] }).default('medium'),
    startDate: text('start_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    endDate: text('end_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    actualEndDate: text('actual_end_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    budget: numeric('budget', { mode: 'number' }),
    parentProject: integer('parent_project_id').references((): AnySQLiteColumn => projects.id, {
      onDelete: 'set null',
    }),
    owner: integer('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('projects_code_idx').on(columns.code),
    index('projects_parent_project_idx').on(columns.parentProject),
    index('projects_owner_idx').on(columns.owner),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
  ],
)

export const projects_rels = sqliteTable(
  'projects_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('projects_rels_order_idx').on(columns.order),
    index('projects_rels_parent_idx').on(columns.parent),
    index('projects_rels_path_idx').on(columns.path),
    index('projects_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [projects.id],
      name: 'projects_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'projects_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const activities = sqliteTable(
  'activities',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    type: text('type', { enum: ['activity', 'sub_activity'] })
      .notNull()
      .default('activity'),
    status: text('status', { enum: ['not_started', 'in_progress', 'blocked', 'done', 'cancelled'] })
      .notNull()
      .default('not_started'),
    priority: text('priority', { enum: ['low', 'medium', 'high', 'urgent'] }).default('medium'),
    startDate: text('start_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    endDate: text('end_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    actualEndDate: text('actual_end_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    estimatedHours: numeric('estimated_hours', { mode: 'number' }),
    actualHours: numeric('actual_hours', { mode: 'number' }),
    project: integer('project_id')
      .notNull()
      .references(() => projects.id, {
        onDelete: 'set null',
      }),
    parentActivity: integer('parent_activity_id').references((): AnySQLiteColumn => activities.id, {
      onDelete: 'set null',
    }),
    owner: integer('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('activities_project_idx').on(columns.project),
    index('activities_parent_activity_idx').on(columns.parentActivity),
    index('activities_owner_idx').on(columns.owner),
    index('activities_updated_at_idx').on(columns.updatedAt),
    index('activities_created_at_idx').on(columns.createdAt),
  ],
)

export const activity_assignments = sqliteTable(
  'activity_assignments',
  {
    id: integer('id').primaryKey(),
    activity: integer('activity_id')
      .notNull()
      .references(() => activities.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    role: text('role'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('activity_assignments_activity_idx').on(columns.activity),
    index('activity_assignments_user_idx').on(columns.user),
    index('activity_assignments_updated_at_idx').on(columns.updatedAt),
    index('activity_assignments_created_at_idx').on(columns.createdAt),
  ],
)

export const comments = sqliteTable(
  'comments',
  {
    id: integer('id').primaryKey(),
    content: text('content').notNull(),
    activity: integer('activity_id').references(() => activities.id, {
      onDelete: 'set null',
    }),
    author: integer('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    type: text('type', { enum: ['staff', 'policy_staff', 'minister', 'activity'] }).notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('comments_activity_idx').on(columns.activity),
    index('comments_author_idx').on(columns.author),
    index('comments_updated_at_idx').on(columns.updatedAt),
    index('comments_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    projectsID: integer('projects_id'),
    activitiesID: integer('activities_id'),
    'activity-assignmentsID': integer('activity_assignments_id'),
    commentsID: integer('comments_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_activities_id_idx').on(columns.activitiesID),
    index('payload_locked_documents_rels_activity_assignments_id_idx').on(
      columns['activity-assignmentsID'],
    ),
    index('payload_locked_documents_rels_comments_id_idx').on(columns.commentsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['activitiesID']],
      foreignColumns: [activities.id],
      name: 'payload_locked_documents_rels_activities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['activity-assignmentsID']],
      foreignColumns: [activity_assignments.id],
      name: 'payload_locked_documents_rels_activity_assignments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['commentsID']],
      foreignColumns: [comments.id],
      name: 'payload_locked_documents_rels_comments_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [projects_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_projects = relations(projects, ({ one, many }) => ({
  parentProject: one(projects, {
    fields: [projects.parentProject],
    references: [projects.id],
    relationName: 'parentProject',
  }),
  owner: one(users, {
    fields: [projects.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  _rels: many(projects_rels, {
    relationName: '_rels',
  }),
}))
export const relations_activities = relations(activities, ({ one }) => ({
  project: one(projects, {
    fields: [activities.project],
    references: [projects.id],
    relationName: 'project',
  }),
  parentActivity: one(activities, {
    fields: [activities.parentActivity],
    references: [activities.id],
    relationName: 'parentActivity',
  }),
  owner: one(users, {
    fields: [activities.owner],
    references: [users.id],
    relationName: 'owner',
  }),
}))
export const relations_activity_assignments = relations(activity_assignments, ({ one }) => ({
  activity: one(activities, {
    fields: [activity_assignments.activity],
    references: [activities.id],
    relationName: 'activity',
  }),
  user: one(users, {
    fields: [activity_assignments.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_comments = relations(comments, ({ one }) => ({
  activity: one(activities, {
    fields: [comments.activity],
    references: [activities.id],
    relationName: 'activity',
  }),
  author: one(users, {
    fields: [comments.author],
    references: [users.id],
    relationName: 'author',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    activitiesID: one(activities, {
      fields: [payload_locked_documents_rels.activitiesID],
      references: [activities.id],
      relationName: 'activities',
    }),
    'activity-assignmentsID': one(activity_assignments, {
      fields: [payload_locked_documents_rels['activity-assignmentsID']],
      references: [activity_assignments.id],
      relationName: 'activity-assignments',
    }),
    commentsID: one(comments, {
      fields: [payload_locked_documents_rels.commentsID],
      references: [comments.id],
      relationName: 'comments',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  projects: typeof projects
  projects_rels: typeof projects_rels
  activities: typeof activities
  activity_assignments: typeof activity_assignments
  comments: typeof comments
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_projects_rels: typeof relations_projects_rels
  relations_projects: typeof relations_projects
  relations_activities: typeof relations_activities
  relations_activity_assignments: typeof relations_activity_assignments
  relations_comments: typeof relations_comments
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-d1-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
